version = 0.1

[default.deploy.parameters]
stack_name = "elhoushy-image-pipeline"
resolve_s3 = true
s3_prefix = "elhoushy-image-pipeline"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketPrefix=\"elhoushy-img\" WatermarkText=\"PREVIEW\""
